import type { GameSettingData } from '../types'

export const MOCK_DATA: GameSettingData[] = [
  // 1-5 (原有的電子類)
  {
    key: '1',
    station: 'FM',
    category: '電子',
    vendorName: 'ATG',
    jackpotSettlement: '停用',
    contribution: 0,
    gameCap: 0.06,
    negativeProfit: '承擔',
    settlementType: '週結',
    settlementTime: '(每週日-23:59:59)',
    remark:
      '台幣通道: 累計1萬以上結清\n* 交易方式1: 10萬以內-採匯款方式結清\n* 交易方式2: 10萬以上-採現金方式面交',
  },
  {
    key: '2',
    station: 'FM',
    category: '電子',
    vendorName: 'QT',
    jackpotSettlement: '停用',
    contribution: 0,
    gameCap: 0.06,
    negativeProfit: '不承擔',
    settlementType: '月結',
    settlementTime: '(每月最後一天-23:59:59)',
    remark:
      '台幣通道: 遊戲平台商務表示，金額不大可累計(千元亦可用USDT\n* 交易方式1: 10萬以內-採USDT方式結清\n* 交易方式2: 10萬以上-採現金方式面交',
  },
  {
    key: '3',
    station: 'FM',
    category: '電子',
    vendorName: 'FM',
    jackpotSettlement: '停用',
    contribution: 0,
    gameCap: 0.06,
    negativeProfit: '承擔',
    settlementType: '週結',
    settlementTime: '(每週日-23:59:59)',
    remark:
      '台幣通道: 累計1萬以上結清\n* 交易方式1: 10萬以內-採匯款方式結清\n* 交易方式2: 10萬以上-採現金方式面交',
  },
  {
    key: '4',
    station: 'FM',
    category: '電子',
    vendorName: 'RSG',
    jackpotSettlement: '啟用',
    contribution: 0.5,
    gameCap: 0.06,
    negativeProfit: '不承擔',
    settlementType: '月結',
    settlementTime: '(每月最後一天-23:59:59)',
    remark:
      '台幣通道: 遊戲平台商務表示，金額不大可累計(千元亦可用USDT\n* 交易方式1: 10萬以內-採USDT方式結清\n* 交易方式2: 10萬以上-採現金方式面交',
  },
  {
    key: '5',
    station: 'FM',
    category: '電子',
    vendorName: 'BNG',
    jackpotSettlement: '停用',
    contribution: 0,
    gameCap: 0.06,
    negativeProfit: '承擔',
    settlementType: '週結',
    settlementTime: '(每週日-23:59:59)',
    remark:
      '台幣通道: 累計1萬以上結清\n* 交易方式1: 10萬以內-採匯款方式結清\n* 交易方式2: 10萬以上-採現金方式面交',
  },
  // 6-10 (更多電子與真人)
  {
    key: '6',
    station: 'FM',
    category: '電子',
    vendorName: 'JDB',
    jackpotSettlement: '啟用',
    contribution: 0.2,
    gameCap: 0.06,
    negativeProfit: '承擔',
    settlementType: '週結',
    settlementTime: '(每週日-23:59:59)',
    remark: '暫無特殊備註，依照平台標準合約執行。',
  },
  {
    key: '7',
    station: 'FM',
    category: '真人',
    vendorName: 'EVO',
    jackpotSettlement: '停用',
    contribution: 0,
    gameCap: 0.05,
    negativeProfit: '不承擔',
    settlementType: '月結',
    settlementTime: '(每月最後一天-23:59:59)',
    remark: '需注意匯差問題，建議使用 USDT 結算。',
  },
  {
    key: '8',
    station: 'FM',
    category: '電子',
    vendorName: 'PP',
    jackpotSettlement: '啟用',
    contribution: 0.5,
    gameCap: 0.07,
    negativeProfit: '承擔',
    settlementType: '週結',
    settlementTime: '(每週日-23:59:59)',
    remark: '台幣通道: 累計1萬以上結清\n* 優先採 USDT 結算',
  },
  {
    key: '9',
    station: 'FM',
    category: '真人',
    vendorName: 'DG',
    jackpotSettlement: '停用',
    contribution: 0,
    gameCap: 0.05,
    negativeProfit: '承擔',
    settlementType: '月結',
    settlementTime: '(每月最後一天-23:59:59)',
    remark: '每月 5 號前需完成對帳。',
  },
  {
    key: '10',
    station: 'FM',
    category: '電子',
    vendorName: 'PG',
    jackpotSettlement: '啟用',
    contribution: 0.3,
    gameCap: 0.06,
    negativeProfit: '不承擔',
    settlementType: '週結',
    settlementTime: '(每週日-23:59:59)',
    remark: '台幣通道: 累計1萬以上結清\n* 交易方式: 採匯款方式結清',
  },
  // 11-15 (體育與其他電子)
  {
    key: '11',
    station: 'FM',
    category: '體育',
    vendorName: 'CMD',
    jackpotSettlement: '停用',
    contribution: 0,
    gameCap: 0.08,
    negativeProfit: '承擔',
    settlementType: '月結',
    settlementTime: '(每月最後一天-23:59:59)',
    remark: '體育類別結算週期較長，需預留 3 天作業時間。',
  },
  {
    key: '12',
    station: 'FM',
    category: '電子',
    vendorName: 'CQ9',
    jackpotSettlement: '停用',
    contribution: 0,
    gameCap: 0.06,
    negativeProfit: '不承擔',
    settlementType: '週結',
    settlementTime: '(每週日-23:59:59)',
    remark: '台幣通道: 遊戲平台商務表示，金額不大可累計。',
  },
  {
    key: '13',
    station: 'FM',
    category: '真人',
    vendorName: 'SA',
    jackpotSettlement: '停用',
    contribution: 0,
    gameCap: 0.05,
    negativeProfit: '承擔',
    settlementType: '月結',
    settlementTime: '(每月最後一天-23:59:59)',
    remark: '暫無備註。',
  },
  {
    key: '14',
    station: 'FM',
    category: '體育',
    vendorName: 'SABA',
    jackpotSettlement: '停用',
    contribution: 0,
    gameCap: 0.08,
    negativeProfit: '不承擔',
    settlementType: '月結',
    settlementTime: '(每月最後一天-23:59:59)',
    remark: '配合賽事結算，可能會延遲一天。',
  },
  {
    key: '15',
    station: 'FM',
    category: '電子',
    vendorName: 'FC',
    jackpotSettlement: '啟用',
    contribution: 0.1,
    gameCap: 0.06,
    negativeProfit: '承擔',
    settlementType: '週結',
    settlementTime: '(每週日-23:59:59)',
    remark: '小額可累計至下週。',
  },
  // 16-20
  {
    key: '16',
    station: 'FM',
    category: '真人',
    vendorName: 'WM',
    jackpotSettlement: '停用',
    contribution: 0,
    gameCap: 0.05,
    negativeProfit: '承擔',
    settlementType: '週結',
    settlementTime: '(每週日-23:59:59)',
    remark:
      '台幣通道: 累計1萬以上結清\n* 交易方式1: 10萬以內-採匯款方式結清\n* 交易方式2: 10萬以上-採現金方式面交',
  },
  {
    key: '17',
    station: 'FM',
    category: '電子',
    vendorName: 'KA',
    jackpotSettlement: '停用',
    contribution: 0,
    gameCap: 0.06,
    negativeProfit: '不承擔',
    settlementType: '月結',
    settlementTime: '(每月最後一天-23:59:59)',
    remark: '僅接受 USDT 結算。',
  },
  {
    key: '18',
    station: 'FM',
    category: '電子',
    vendorName: 'VA',
    jackpotSettlement: '啟用',
    contribution: 0.5,
    gameCap: 0.06,
    negativeProfit: '承擔',
    settlementType: '週結',
    settlementTime: '(每週日-23:59:59)',
    remark: '正常每週一結算。',
  },
  {
    key: '19',
    station: 'FM',
    category: '真人',
    vendorName: 'OG',
    jackpotSettlement: '停用',
    contribution: 0,
    gameCap: 0.05,
    negativeProfit: '不承擔',
    settlementType: '月結',
    settlementTime: '(每月最後一天-23:59:59)',
    remark: '需注意手續費扣除。',
  },
  {
    key: '20',
    station: 'FM',
    category: '體育',
    vendorName: 'OB',
    jackpotSettlement: '停用',
    contribution: 0,
    gameCap: 0.08,
    negativeProfit: '承擔',
    settlementType: '月結',
    settlementTime: '(每月最後一天-23:59:59)',
    remark: '台幣通道: 累計5萬以上結清。',
  },
  // 21-25
  {
    key: '21',
    station: 'FM',
    category: '電子',
    vendorName: 'GR',
    jackpotSettlement: '啟用',
    contribution: 0.25,
    gameCap: 0.06,
    negativeProfit: '不承擔',
    settlementType: '週結',
    settlementTime: '(每週日-23:59:59)',
    remark: '暫無特殊備註。',
  },
  {
    key: '22',
    station: 'FM',
    category: '電子',
    vendorName: 'SP',
    jackpotSettlement: '停用',
    contribution: 0,
    gameCap: 0.06,
    negativeProfit: '承擔',
    settlementType: '週結',
    settlementTime: '(每週日-23:59:59)',
    remark:
      '台幣通道: 累計1萬以上結清\n* 交易方式1: 10萬以內-採匯款方式結清\n* 交易方式2: 10萬以上-採現金方式面交',
  },
  {
    key: '23',
    station: 'FM',
    category: '真人',
    vendorName: 'SEXY',
    jackpotSettlement: '停用',
    contribution: 0,
    gameCap: 0.05,
    negativeProfit: '不承擔',
    settlementType: '月結',
    settlementTime: '(每月最後一天-23:59:59)',
    remark: '結算日若遇假日順延至下一個工作日。',
  },
  {
    key: '24',
    station: 'FM',
    category: '電子',
    vendorName: 'TP',
    jackpotSettlement: '啟用',
    contribution: 0.4,
    gameCap: 0.06,
    negativeProfit: '承擔',
    settlementType: '週結',
    settlementTime: '(每週日-23:59:59)',
    remark: '需確認彩金貢獻比例是否正確。',
  },
  {
    key: '25',
    station: 'FM',
    category: '彩票',
    vendorName: 'WIN539',
    jackpotSettlement: '停用',
    contribution: 0,
    gameCap: 0.04,
    negativeProfit: '承擔',
    settlementType: '週結',
    settlementTime: '(每週日-23:59:59)',
    remark: '彩票類別獨立結算。',
  },
]
