import type { GroupDataType } from '../types'

export const MOCK_DATA: GroupDataType[] = [
  // ==========================================
  // 1. 儲值 (Deposit) - 共 25 筆
  // ==========================================
  {
    key: 'd-1',
    category: '儲值',
    type: 'ATM',
    name: 'CKPAY',
    displayName: 'ATM-CKPAY',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 20000,
    freeFeeCount: 3,
    feePercent: 4,
    minFeeAmount: 60,
    totalDeposit: 130000,
    totalFee: 1300,
    grandTotal: 131300,
    status: true,
    remark: '',
  },
  {
    key: 'd-2',
    category: '儲值',
    type: '超商(CVS)',
    name: '98PAY',
    displayName: '超商(CVS)-98PAY',
    rate: 1,
    minDeposit: 100,
    maxDeposit: 50000,
    freeFeeCount: 3,
    feePercent: 0,
    minFeeAmount: 10,
    totalDeposit: 12330005,
    totalFee: 780,
    grandTotal: 12330785,
    status: true,
    remark: '重點觀察項目',
  },
  {
    key: 'd-3',
    category: '儲值',
    type: '信用卡',
    name: 'GreenPay',
    displayName: '信用卡-GreenPay',
    rate: 1,
    minDeposit: 3000,
    maxDeposit: 100000,
    freeFeeCount: 0,
    feePercent: 2.5,
    minFeeAmount: 50,
    totalDeposit: 450000,
    totalFee: 11250,
    grandTotal: 461250,
    status: true,
    remark: '高額手續費',
  },
  {
    key: 'd-4',
    category: '儲值',
    type: 'USDT',
    name: 'TRC20',
    displayName: 'USDT-TRC20',
    rate: 31.5,
    minDeposit: 100,
    maxDeposit: 10000,
    freeFeeCount: 999,
    feePercent: 0,
    minFeeAmount: 0,
    totalDeposit: 3150000,
    totalFee: 0,
    grandTotal: 3150000,
    status: true,
    remark: '大額專用通道',
  },
  {
    key: 'd-5',
    category: '儲值',
    type: 'ATM',
    name: 'Spay',
    displayName: 'ATM-Spay',
    rate: 1,
    minDeposit: 500,
    maxDeposit: 30000,
    freeFeeCount: 5,
    feePercent: 1,
    minFeeAmount: 15,
    totalDeposit: 80000,
    totalFee: 800,
    grandTotal: 80800,
    status: false,
    remark: '維護中',
  },
  {
    key: 'd-6',
    category: '儲值',
    type: 'Super-ATM',
    name: 'QuickPay',
    displayName: 'Super-ATM-QuickPay',
    rate: 1,
    minDeposit: 2000,
    maxDeposit: 50000,
    freeFeeCount: 0,
    feePercent: 1.5,
    minFeeAmount: 30,
    totalDeposit: 600000,
    totalFee: 9000,
    grandTotal: 609000,
    status: true,
    remark: '',
  },
  {
    key: 'd-7',
    category: '儲值',
    type: '超商(CVS)',
    name: 'OKPay',
    displayName: '超商(CVS)-OKPay',
    rate: 1,
    minDeposit: 100,
    maxDeposit: 20000,
    freeFeeCount: 3,
    feePercent: 0,
    minFeeAmount: 25,
    totalDeposit: 55000,
    totalFee: 550,
    grandTotal: 55550,
    status: true,
    remark: '',
  },
  {
    key: 'd-8',
    category: '儲值',
    type: '電子支付',
    name: 'JKOPay',
    displayName: '電支-街口',
    rate: 1,
    minDeposit: 100,
    maxDeposit: 5000,
    freeFeeCount: 0,
    feePercent: 3,
    minFeeAmount: 10,
    totalDeposit: 15000,
    totalFee: 450,
    grandTotal: 15450,
    status: true,
    remark: '小額測試',
  },
  {
    key: 'd-9',
    category: '儲值',
    type: 'ATM',
    name: 'FubonPay',
    displayName: 'ATM-富邦',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 30000,
    freeFeeCount: 5,
    feePercent: 1,
    minFeeAmount: 20,
    totalDeposit: 220000,
    totalFee: 2200,
    grandTotal: 222200,
    status: true,
    remark: '',
  },
  {
    key: 'd-10',
    category: '儲值',
    type: '信用卡',
    name: 'BluePay',
    displayName: '信用卡-BluePay',
    rate: 1,
    minDeposit: 5000,
    maxDeposit: 200000,
    freeFeeCount: 0,
    feePercent: 3,
    minFeeAmount: 100,
    totalDeposit: 1500000,
    totalFee: 45000,
    grandTotal: 1545000,
    status: true,
    remark: 'VIP專用',
  },
  {
    key: 'd-11',
    category: '儲值',
    type: '超商(CVS)',
    name: 'FamilyPay',
    displayName: '超商(CVS)-全家',
    rate: 1,
    minDeposit: 100,
    maxDeposit: 20000,
    freeFeeCount: 3,
    feePercent: 0,
    minFeeAmount: 30,
    totalDeposit: 78000,
    totalFee: 780,
    grandTotal: 78780,
    status: true,
    remark: '',
  },
  {
    key: 'd-12',
    category: '儲值',
    type: 'USDT',
    name: 'ERC20',
    displayName: 'USDT-ERC20',
    rate: 31.2,
    minDeposit: 100,
    maxDeposit: 5000,
    freeFeeCount: 99,
    feePercent: 0.5,
    minFeeAmount: 5,
    totalDeposit: 624000,
    totalFee: 3120,
    grandTotal: 627120,
    status: true,
    remark: '',
  },
  {
    key: 'd-13',
    category: '儲值',
    type: 'ATM',
    name: 'MegaPay',
    displayName: 'ATM-兆豐',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 20000,
    freeFeeCount: 2,
    feePercent: 2,
    minFeeAmount: 20,
    totalDeposit: 45000,
    totalFee: 900,
    grandTotal: 45900,
    status: false,
    remark: '連線異常',
  },
  {
    key: 'd-14',
    category: '儲值',
    type: '電子支付',
    name: 'LinePay',
    displayName: '電支-Line',
    rate: 1,
    minDeposit: 100,
    maxDeposit: 5000,
    freeFeeCount: 0,
    feePercent: 3.5,
    minFeeAmount: 10,
    totalDeposit: 0,
    totalFee: 0,
    grandTotal: 0,
    status: false,
    remark: '尚未開通',
  },
  {
    key: 'd-15',
    category: '儲值',
    type: 'ATM',
    name: 'BotPay',
    displayName: 'ATM-台銀',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 30000,
    freeFeeCount: 5,
    feePercent: 1,
    minFeeAmount: 20,
    totalDeposit: 560000,
    totalFee: 5600,
    grandTotal: 565600,
    status: true,
    remark: '',
  },
  {
    key: 'd-16',
    category: '儲值',
    type: '超商(CVS)',
    name: 'HiLife',
    displayName: '超商(CVS)-萊爾富',
    rate: 1,
    minDeposit: 100,
    maxDeposit: 20000,
    freeFeeCount: 3,
    feePercent: 0,
    minFeeAmount: 25,
    totalDeposit: 23000,
    totalFee: 230,
    grandTotal: 23230,
    status: true,
    remark: '',
  },
  {
    key: 'd-17',
    category: '儲值',
    type: 'Super-ATM',
    name: 'SpeedPay',
    displayName: 'Super-ATM-Speed',
    rate: 1,
    minDeposit: 5000,
    maxDeposit: 100000,
    freeFeeCount: 0,
    feePercent: 1.2,
    minFeeAmount: 50,
    totalDeposit: 2500000,
    totalFee: 30000,
    grandTotal: 2530000,
    status: true,
    remark: '',
  },
  {
    key: 'd-18',
    category: '儲值',
    type: '信用卡',
    name: 'JCB',
    displayName: '信用卡-JCB',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 50000,
    freeFeeCount: 0,
    feePercent: 2.8,
    minFeeAmount: 50,
    totalDeposit: 89000,
    totalFee: 2492,
    grandTotal: 91492,
    status: true,
    remark: '',
  },
  {
    key: 'd-19',
    category: '儲值',
    type: 'ATM',
    name: 'SinoPay',
    displayName: 'ATM-永豐',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 20000,
    freeFeeCount: 3,
    feePercent: 1.2,
    minFeeAmount: 20,
    totalDeposit: 145000,
    totalFee: 1740,
    grandTotal: 146740,
    status: true,
    remark: '',
  },
  {
    key: 'd-20',
    category: '儲值',
    type: '超商(CVS)',
    name: '7-11',
    displayName: '超商(CVS)-IBON',
    rate: 1,
    minDeposit: 100,
    maxDeposit: 20000,
    freeFeeCount: 3,
    feePercent: 0,
    minFeeAmount: 35,
    totalDeposit: 99000,
    totalFee: 990,
    grandTotal: 99990,
    status: true,
    remark: '',
  },
  {
    key: 'd-21',
    category: '儲值',
    type: 'USDT',
    name: 'BEP20',
    displayName: 'USDT-BEP20',
    rate: 31.4,
    minDeposit: 50,
    maxDeposit: 5000,
    freeFeeCount: 99,
    feePercent: 0.2,
    minFeeAmount: 2,
    totalDeposit: 15700,
    totalFee: 31,
    grandTotal: 15731,
    status: true,
    remark: '',
  },
  {
    key: 'd-22',
    category: '儲值',
    type: '信用卡',
    name: 'MasterCard',
    displayName: '信用卡-Master',
    rate: 1,
    minDeposit: 2000,
    maxDeposit: 80000,
    freeFeeCount: 0,
    feePercent: 2.6,
    minFeeAmount: 45,
    totalDeposit: 330000,
    totalFee: 8580,
    grandTotal: 338580,
    status: true,
    remark: '',
  },
  {
    key: 'd-23',
    category: '儲值',
    type: '電子支付',
    name: 'EasyPay',
    displayName: '電支-悠遊付',
    rate: 1,
    minDeposit: 100,
    maxDeposit: 3000,
    freeFeeCount: 0,
    feePercent: 3.2,
    minFeeAmount: 10,
    totalDeposit: 8500,
    totalFee: 272,
    grandTotal: 8772,
    status: true,
    remark: '',
  },
  {
    key: 'd-24',
    category: '儲值',
    type: 'ATM',
    name: 'HNCB',
    displayName: 'ATM-華南',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 30000,
    freeFeeCount: 3,
    feePercent: 1.1,
    minFeeAmount: 20,
    totalDeposit: 180000,
    totalFee: 1980,
    grandTotal: 181980,
    status: true,
    remark: '',
  },
  {
    key: 'd-25',
    category: '儲值',
    type: '超商(CVS)',
    name: 'CvsPay',
    displayName: '超商(CVS)-通用',
    rate: 1,
    minDeposit: 100,
    maxDeposit: 15000,
    freeFeeCount: 3,
    feePercent: 0,
    minFeeAmount: 25,
    totalDeposit: 42000,
    totalFee: 420,
    grandTotal: 42420,
    status: false,
    remark: '合約更新中',
  },

  // ==========================================
  // 2. 託售 (Withdraw) - 共 25 筆
  // ==========================================
  {
    key: 'w-1',
    category: '託售',
    type: '銀行卡',
    name: '台新銀行',
    displayName: '銀行卡-台新銀行',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 50000,
    freeFeeCount: 0,
    feePercent: 1,
    minFeeAmount: 15,
    totalDeposit: 500000,
    totalFee: 5000,
    grandTotal: 505000,
    status: true,
    remark: '出款專用',
  },
  {
    key: 'w-2',
    category: '託售',
    type: '銀行卡',
    name: '中國信託',
    displayName: '銀行卡-中國信託',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 200000,
    freeFeeCount: 1,
    feePercent: 0,
    minFeeAmount: 15,
    totalDeposit: 1200000,
    totalFee: 300,
    grandTotal: 1200300,
    status: true,
    remark: '主要出款銀行',
  },
  {
    key: 'w-3',
    category: '託售',
    type: 'USDT',
    name: 'ERC20',
    displayName: 'USDT-ERC20',
    rate: 31.2,
    minDeposit: 500,
    maxDeposit: 50000,
    freeFeeCount: 0,
    feePercent: 0,
    minFeeAmount: 10,
    totalDeposit: 0,
    totalFee: 0,
    grandTotal: 0,
    status: false,
    remark: '暫停使用',
  },
  {
    key: 'w-4',
    category: '託售',
    type: '銀行卡',
    name: '國泰世華',
    displayName: '銀行卡-國泰世華',
    rate: 1,
    minDeposit: 500,
    maxDeposit: 100000,
    freeFeeCount: 0,
    feePercent: 0,
    minFeeAmount: 15,
    totalDeposit: 980000,
    totalFee: 450,
    grandTotal: 980450,
    status: true,
    remark: '',
  },
  {
    key: 'w-5',
    category: '託售',
    type: '銀行卡',
    name: '玉山銀行',
    displayName: '銀行卡-玉山',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 50000,
    freeFeeCount: 0,
    feePercent: 0,
    minFeeAmount: 15,
    totalDeposit: 340000,
    totalFee: 300,
    grandTotal: 340300,
    status: true,
    remark: '',
  },
  {
    key: 'w-6',
    category: '託售',
    type: '銀行卡',
    name: '郵局',
    displayName: '銀行卡-郵局',
    rate: 1,
    minDeposit: 500,
    maxDeposit: 20000,
    freeFeeCount: 0,
    feePercent: 0,
    minFeeAmount: 10,
    totalDeposit: 120000,
    totalFee: 600,
    grandTotal: 120600,
    status: true,
    remark: '小額出款',
  },
  {
    key: 'w-7',
    category: '託售',
    type: 'USDT',
    name: 'TRC20',
    displayName: 'USDT-TRC20-Out',
    rate: 31.0,
    minDeposit: 1000,
    maxDeposit: 100000,
    freeFeeCount: 0,
    feePercent: 0.1,
    minFeeAmount: 1,
    totalDeposit: 1550000,
    totalFee: 1550,
    grandTotal: 1551550,
    status: true,
    remark: '出款主通道',
  },
  {
    key: 'w-8',
    category: '託售',
    type: '銀行卡',
    name: '台北富邦',
    displayName: '銀行卡-台北富邦',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 100000,
    freeFeeCount: 0,
    feePercent: 0,
    minFeeAmount: 15,
    totalDeposit: 750000,
    totalFee: 750,
    grandTotal: 750750,
    status: true,
    remark: '',
  },
  {
    key: 'w-9',
    category: '託售',
    type: '銀行卡',
    name: '第一銀行',
    displayName: '銀行卡-第一銀行',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 60000,
    freeFeeCount: 0,
    feePercent: 0,
    minFeeAmount: 15,
    totalDeposit: 420000,
    totalFee: 420,
    grandTotal: 420420,
    status: true,
    remark: '',
  },
  {
    key: 'w-10',
    category: '託售',
    type: '銀行卡',
    name: '華南銀行',
    displayName: '銀行卡-華南銀行',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 50000,
    freeFeeCount: 0,
    feePercent: 0,
    minFeeAmount: 15,
    totalDeposit: 280000,
    totalFee: 280,
    grandTotal: 280280,
    status: true,
    remark: '',
  },
  {
    key: 'w-11',
    category: '託售',
    type: '銀行卡',
    name: '彰化銀行',
    displayName: '銀行卡-彰化銀行',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 50000,
    freeFeeCount: 0,
    feePercent: 0,
    minFeeAmount: 15,
    totalDeposit: 190000,
    totalFee: 190,
    grandTotal: 190190,
    status: true,
    remark: '',
  },
  {
    key: 'w-12',
    category: '託售',
    type: '銀行卡',
    name: '上海銀行',
    displayName: '銀行卡-上海銀行',
    rate: 1,
    minDeposit: 2000,
    maxDeposit: 100000,
    freeFeeCount: 0,
    feePercent: 0,
    minFeeAmount: 15,
    totalDeposit: 310000,
    totalFee: 310,
    grandTotal: 310310,
    status: true,
    remark: '',
  },
  {
    key: 'w-13',
    category: '託售',
    type: '銀行卡',
    name: '高雄銀行',
    displayName: '銀行卡-高雄銀行',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 30000,
    freeFeeCount: 0,
    feePercent: 0,
    minFeeAmount: 15,
    totalDeposit: 85000,
    totalFee: 85,
    grandTotal: 85085,
    status: true,
    remark: '',
  },
  {
    key: 'w-14',
    category: '託售',
    type: '銀行卡',
    name: '兆豐銀行',
    displayName: '銀行卡-兆豐銀行',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 100000,
    freeFeeCount: 0,
    feePercent: 0,
    minFeeAmount: 15,
    totalDeposit: 660000,
    totalFee: 660,
    grandTotal: 660660,
    status: true,
    remark: '',
  },
  {
    key: 'w-15',
    category: '託售',
    type: '銀行卡',
    name: '花旗銀行',
    displayName: '銀行卡-花旗',
    rate: 1,
    minDeposit: 5000,
    maxDeposit: 200000,
    freeFeeCount: 0,
    feePercent: 0,
    minFeeAmount: 30,
    totalDeposit: 0,
    totalFee: 0,
    grandTotal: 0,
    status: false,
    remark: '業務整併中',
  },
  {
    key: 'w-16',
    category: '託售',
    type: '銀行卡',
    name: '渣打銀行',
    displayName: '銀行卡-渣打',
    rate: 1,
    minDeposit: 2000,
    maxDeposit: 80000,
    freeFeeCount: 0,
    feePercent: 0,
    minFeeAmount: 20,
    totalDeposit: 150000,
    totalFee: 150,
    grandTotal: 150150,
    status: true,
    remark: '',
  },
  {
    key: 'w-17',
    category: '託售',
    type: '銀行卡',
    name: '匯豐銀行',
    displayName: '銀行卡-匯豐',
    rate: 1,
    minDeposit: 5000,
    maxDeposit: 150000,
    freeFeeCount: 0,
    feePercent: 0,
    minFeeAmount: 25,
    totalDeposit: 220000,
    totalFee: 220,
    grandTotal: 220220,
    status: true,
    remark: '',
  },
  {
    key: 'w-18',
    category: '託售',
    type: '銀行卡',
    name: '新光銀行',
    displayName: '銀行卡-新光',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 60000,
    freeFeeCount: 0,
    feePercent: 0,
    minFeeAmount: 15,
    totalDeposit: 330000,
    totalFee: 330,
    grandTotal: 330330,
    status: true,
    remark: '',
  },
  {
    key: 'w-19',
    category: '託售',
    type: '銀行卡',
    name: '聯邦銀行',
    displayName: '銀行卡-聯邦',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 50000,
    freeFeeCount: 0,
    feePercent: 0,
    minFeeAmount: 15,
    totalDeposit: 290000,
    totalFee: 290,
    grandTotal: 290290,
    status: true,
    remark: '',
  },
  {
    key: 'w-20',
    category: '託售',
    type: '銀行卡',
    name: '遠東商銀',
    displayName: '銀行卡-遠東',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 40000,
    freeFeeCount: 0,
    feePercent: 0,
    minFeeAmount: 15,
    totalDeposit: 180000,
    totalFee: 180,
    grandTotal: 180180,
    status: true,
    remark: '',
  },
  {
    key: 'w-21',
    category: '託售',
    type: '銀行卡',
    name: '元大銀行',
    displayName: '銀行卡-元大',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 70000,
    freeFeeCount: 0,
    feePercent: 0,
    minFeeAmount: 15,
    totalDeposit: 410000,
    totalFee: 410,
    grandTotal: 410410,
    status: true,
    remark: '',
  },
  {
    key: 'w-22',
    category: '託售',
    type: '銀行卡',
    name: '永豐銀行',
    displayName: '銀行卡-永豐',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 80000,
    freeFeeCount: 0,
    feePercent: 0,
    minFeeAmount: 15,
    totalDeposit: 550000,
    totalFee: 550,
    grandTotal: 550550,
    status: true,
    remark: '',
  },
  {
    key: 'w-23',
    category: '託售',
    type: '銀行卡',
    name: '凱基銀行',
    displayName: '銀行卡-凱基',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 50000,
    freeFeeCount: 0,
    feePercent: 0,
    minFeeAmount: 15,
    totalDeposit: 160000,
    totalFee: 160,
    grandTotal: 160160,
    status: true,
    remark: '',
  },
  {
    key: 'w-24',
    category: '託售',
    type: '銀行卡',
    name: '星展銀行',
    displayName: '銀行卡-星展',
    rate: 1,
    minDeposit: 3000,
    maxDeposit: 120000,
    freeFeeCount: 0,
    feePercent: 0,
    minFeeAmount: 25,
    totalDeposit: 380000,
    totalFee: 380,
    grandTotal: 380380,
    status: true,
    remark: '',
  },
  {
    key: 'w-25',
    category: '託售',
    type: '銀行卡',
    name: '日盛銀行',
    displayName: '銀行卡-日盛',
    rate: 1,
    minDeposit: 1000,
    maxDeposit: 30000,
    freeFeeCount: 0,
    feePercent: 0,
    minFeeAmount: 15,
    totalDeposit: 95000,
    totalFee: 95,
    grandTotal: 95095,
    status: false,
    remark: '已合併',
  },
]
