import type { GameDataType } from '../types'

export const MOCK_DATA: GameDataType[] = [
  {
    key: '1',
    type: '電子',
    gameId: 122,
    gameCode: 'golden-seth',
    gameName: '戰神賽特II',
    rtp: '96.89%',
    device: '所有裝置',
    status: true,
    remark: '',
  },
  {
    key: '2',
    type: '電子',
    gameId: 121,
    gameCode: 'wuxia-caishen',
    gameName: '武俠',
    rtp: '97%',
    device: '所有裝置',
    status: true,
    remark: '',
  },
  {
    key: '3',
    type: '電子',
    gameId: 114,
    gameCode: 'egyptian-mythology',
    gameName: '戰神賽特',
    rtp: '96.89%',
    device: '所有裝置',
    status: true,
    remark: '',
  },
  {
    key: '4',
    type: '電子',
    gameId: 118,
    gameCode: 'son-go-ku',
    gameName: '孫行者',
    rtp: '96.7%',
    device: '所有裝置',
    status: true,
    remark: '',
  },
  {
    key: '5',
    type: '電子',
    gameId: 75,
    gameCode: 'vampire-hunter',
    gameName: '惡魔獵人',
    rtp: '95.74%',
    device: '所有裝置',
    status: true,
    remark: '',
  },
  {
    key: '6',
    type: '電子',
    gameId: 40,
    gameCode: 'sexyfox',
    gameName: '狐群狗黨',
    rtp: '96.31%',
    device: '所有裝置',
    status: true,
    remark: '',
  },
  {
    key: '7',
    type: '電子',
    gameId: 88,
    gameCode: 'fu-lu-so',
    gameName: '三星報喜',
    rtp: '96.32%',
    device: '所有裝置',
    status: false,
    remark: '7/11 遊戲RTP有問題，緊急下架',
  },
  {
    key: '8',
    type: '電子',
    gameId: 61,
    gameCode: 'crazy-alice',
    gameName: '仙境狂想曲',
    rtp: '96.75%',
    device: '所有裝置',
    status: false,
    remark: '維護中',
  },
  {
    key: '9',
    type: '電子',
    gameId: 130,
    gameCode: 'thor-hammer',
    gameName: '雷神之錘',
    rtp: '97.2%',
    device: '所有裝置',
    status: true,
    remark: '熱門遊戲',
  },
  {
    key: '10',
    type: '電子',
    gameId: 131,
    gameCode: 'mahjong-fa',
    gameName: '麻將發發發',
    rtp: '96.5%',
    device: '所有裝置',
    status: true,
    remark: '',
  },
  {
    key: '11',
    type: '電子',
    gameId: 132,
    gameCode: 'lucky-gem',
    gameName: '幸運寶石',
    rtp: '95.8%',
    device: '所有裝置',
    status: true,
    remark: '',
  },
  {
    key: '12',
    type: '電子',
    gameId: 133,
    gameCode: 'jungle-adventure',
    gameName: '叢林冒險',
    rtp: '96.1%',
    device: '所有裝置',
    status: true,
    remark: '',
  },
  {
    key: '13',
    type: '電子',
    gameId: 134,
    gameCode: 'deep-sea',
    gameName: '深海尋寶',
    rtp: '96.4%',
    device: '所有裝置',
    status: true,
    remark: '',
  },
  {
    key: '14',
    type: '電子',
    gameId: 135,
    gameCode: 'caishen-wins',
    gameName: '財神到',
    rtp: '97.5%',
    device: '所有裝置',
    status: true,
    remark: '新年活動主打',
  },
  {
    key: '15',
    type: '電子',
    gameId: 136,
    gameCode: 'crazy-fruit',
    gameName: '瘋狂水果',
    rtp: '95.5%',
    device: '所有裝置',
    status: true,
    remark: '',
  },
  {
    key: '16',
    type: '電子',
    gameId: 137,
    gameCode: 'cleopatra',
    gameName: '埃及豔后',
    rtp: '96.0%',
    device: '所有裝置',
    status: true,
    remark: '',
  },
  {
    key: '17',
    type: '電子',
    gameId: 138,
    gameCode: 'journey-west',
    gameName: '西遊記',
    rtp: '96.8%',
    device: '所有裝置',
    status: true,
    remark: '',
  },
  {
    key: '18',
    type: '電子',
    gameId: 139,
    gameCode: 'feng-shen',
    gameName: '封神榜',
    rtp: '96.6%',
    device: '所有裝置',
    status: true,
    remark: '',
  },
  {
    key: '19',
    type: '電子',
    gameId: 140,
    gameCode: 'ninja-legend',
    gameName: '忍者傳說',
    rtp: '96.2%',
    device: '所有裝置',
    status: true,
    remark: '',
  },
  {
    key: '20',
    type: '電子',
    gameId: 141,
    gameCode: 'jurassic',
    gameName: '侏羅紀公園',
    rtp: '97.0%',
    device: '所有裝置',
    status: true,
    remark: '',
  },
  {
    key: '21',
    type: '電子',
    gameId: 142,
    gameCode: 'candy-party',
    gameName: '糖果派對',
    rtp: '95.9%',
    device: '所有裝置',
    status: true,
    remark: '',
  },
  {
    key: '22',
    type: '電子',
    gameId: 143,
    gameCode: 'treasure-hunter',
    gameName: '寶藏獵人',
    rtp: '96.3%',
    device: '所有裝置',
    status: true,
    remark: '',
  },
  {
    key: '23',
    type: '電子',
    gameId: 144,
    gameCode: 'panda-hero',
    gameName: '熊貓大俠',
    rtp: '96.7%',
    device: '所有裝置',
    status: true,
    remark: '',
  },
  {
    key: '24',
    type: '電子',
    gameId: 145,
    gameCode: 'dragon-king',
    gameName: '龍王',
    rtp: '97.1%',
    device: '所有裝置',
    status: true,
    remark: '',
  },
  {
    key: '25',
    type: '電子',
    gameId: 146,
    gameCode: 'lucky-wheel',
    gameName: '幸運輪盤',
    rtp: '95.6%',
    device: '所有裝置',
    status: true,
    remark: '',
  },
]

export const PROVIDERS = [
  { code: 'ATG', count: 36 },
  { code: 'QT', count: 23 },
  { code: 'FM', count: 19 },
  { code: 'RSG', count: 32 },
  { code: 'BNG', count: 20 },
  { code: 'BT', count: 21 },
  { code: 'FG', count: 30 },
  { code: '簽發', count: 22 },
  { code: 'CG', count: 16 },
  { code: 'GB', count: 21 },
]
