import type {
  GameSettlementType,
  BetDetailType,
  JcDetailType,
  RevenueDetailType,
} from '../types'

export const MOCK_DATA: GameSettlementType[] = [
  // --- 原有資料 (1-5) ---
  {
    key: '1',
    agentLevel: '1 / 4 (8)',
    agentName: 'FMCA',
    agentDesc: '(金流/成數代理-主站)',
    category: '電子',
    provider: 'ATG',
    jpSettlement: '停用',
    method: '週結',
    date: '2025/07/10',
    betCount: 1,
    betAmount: 1000,
    validBet: 1000,
    jc: 0,
    jp: 0,
    winAmount: 0,
    lossAmount: 1000,
    jcJpTotal: 0,
    revenueAmount: 60,
    status: 'unpaid',
  },
  {
    key: '2',
    agentLevel: '1 / 7 (51)',
    agentName: 'XOUT',
    agentDesc: '(金流/成數代理-外單位)',
    category: '電子',
    provider: 'QT',
    jpSettlement: '停用',
    method: '月結',
    date: '2025/07/31',
    betCount: 1,
    betAmount: 1000,
    validBet: 1000,
    jc: 0,
    jp: 0,
    winAmount: 500,
    lossAmount: 500,
    jcJpTotal: 0,
    revenueAmount: 30,
    status: 'unpaid',
  },
  {
    key: '3',
    agentLevel: '1 / 5 (4)',
    agentName: 'FMCA02',
    agentDesc: '(金流/返水代理-主站)',
    category: '電子',
    provider: 'FM',
    jpSettlement: '停用',
    method: '週結',
    date: '2025/07/10',
    betCount: 1,
    betAmount: 1000,
    validBet: 1000,
    jc: 0,
    jp: 0,
    winAmount: 750,
    lossAmount: 250,
    jcJpTotal: 0,
    revenueAmount: 15,
    status: 'unpaid',
  },
  {
    key: '4',
    agentLevel: '1 / 4 (13)',
    agentName: 'XFW',
    agentDesc: '(金流/成數+返水代理-外單位)',
    category: '電子',
    provider: 'RSG',
    jpSettlement: '啟用',
    method: '月結',
    date: '2025/07/31',
    betCount: 2,
    betAmount: 1000,
    validBet: 1000,
    jc: 5,
    jp: 0,
    winAmount: 800,
    lossAmount: 200,
    jcJpTotal: 5,
    revenueAmount: 17,
    status: 'unpaid',
  },
  {
    key: '5',
    agentLevel: '1 / 5 (1)',
    agentName: 'W02',
    agentDesc: '(透支-(信用/成數代理-外單位))',
    category: '電子',
    provider: 'BT',
    jpSettlement: '停用',
    method: '月結',
    date: '2025/07/31',
    betCount: 2,
    betAmount: 1000,
    validBet: 1000,
    jc: 0,
    jp: 0,
    winAmount: 0,
    lossAmount: 0,
    jcJpTotal: 0,
    revenueAmount: 0,
    status: 'auditing',
  },
  // --- 新增資料 (6-25) ---
  {
    key: '6',
    agentLevel: '1 / 6 (7)',
    agentName: 'W01',
    agentDesc: '(透支-(信用/成數+返水代理-外單位))',
    category: '電子',
    provider: 'FG',
    jpSettlement: '停用',
    method: '週結',
    date: '2025/07/10',
    betCount: 1,
    betAmount: 1000,
    validBet: 1000,
    jc: 0,
    jp: 0,
    winAmount: 0,
    lossAmount: 0,
    jcJpTotal: 0,
    revenueAmount: 0,
    status: 'unpaid',
  },
  {
    key: '7',
    agentLevel: '1 / 3 (22)',
    agentName: 'KING88',
    agentDesc: '(金流/成數代理-VIP)',
    category: '真人',
    provider: 'EVO',
    jpSettlement: '停用',
    method: '週結',
    date: '2025/07/10',
    betCount: 15,
    betAmount: 50000,
    validBet: 48000,
    jc: 0,
    jp: 0,
    winAmount: 20000,
    lossAmount: 28000,
    jcJpTotal: 0,
    revenueAmount: 1680,
    status: 'paid',
  },
  {
    key: '8',
    agentLevel: '1 / 2 (5)',
    agentName: 'TYA01',
    agentDesc: '(金流/返水代理-測試)',
    category: '體育',
    provider: 'SS',
    jpSettlement: '停用',
    method: '月結',
    date: '2025/07/31',
    betCount: 8,
    betAmount: 3000,
    validBet: 3000,
    jc: 0,
    jp: 0,
    winAmount: 3200,
    lossAmount: -200,
    jcJpTotal: 0,
    revenueAmount: 0,
    status: 'auditing',
  },
  {
    key: '9',
    agentLevel: '1 / 4 (10)',
    agentName: 'GO_PRO',
    agentDesc: '(金流/成數代理-主站)',
    category: '電子',
    provider: 'BNG',
    jpSettlement: '啟用',
    method: '月結',
    date: '2025/07/31',
    betCount: 200,
    betAmount: 25000,
    validBet: 25000,
    jc: 120,
    jp: 50,
    winAmount: 10000,
    lossAmount: 15000,
    jcJpTotal: 170,
    revenueAmount: 900,
    status: 'unpaid',
  },
  {
    key: '10',
    agentLevel: '1 / 8 (2)',
    agentName: 'TEST_USER',
    agentDesc: '(測試帳號)',
    category: '電子',
    provider: 'JDB',
    jpSettlement: '停用',
    method: '週結',
    date: '2025/07/10',
    betCount: 5,
    betAmount: 500,
    validBet: 500,
    jc: 0,
    jp: 0,
    winAmount: 100,
    lossAmount: 400,
    jcJpTotal: 0,
    revenueAmount: 20,
    status: 'paid',
  },
  {
    key: '11',
    agentLevel: '1 / 4 (9)',
    agentName: 'FMCA',
    agentDesc: '(金流/成數代理-主站)',
    category: '真人',
    provider: 'DG',
    jpSettlement: '停用',
    method: '週結',
    date: '2025/07/10',
    betCount: 45,
    betAmount: 12000,
    validBet: 12000,
    jc: 0,
    jp: 0,
    winAmount: 6000,
    lossAmount: 6000,
    jcJpTotal: 0,
    revenueAmount: 360,
    status: 'unpaid',
  },
  {
    key: '12',
    agentLevel: '1 / 5 (11)',
    agentName: 'XOUT',
    agentDesc: '(金流/成數代理-外單位)',
    category: '電子',
    provider: 'PP',
    jpSettlement: '啟用',
    method: '月結',
    date: '2025/07/31',
    betCount: 150,
    betAmount: 8800,
    validBet: 8800,
    jc: 44,
    jp: 0,
    winAmount: 5000,
    lossAmount: 3800,
    jcJpTotal: 44,
    revenueAmount: 228,
    status: 'unpaid',
  },
  {
    key: '13',
    agentLevel: '1 / 3 (15)',
    agentName: 'SUPER_88',
    agentDesc: '(金流/成數代理-VIP)',
    category: '電子',
    provider: 'CQ9',
    jpSettlement: '停用',
    method: '週結',
    date: '2025/07/10',
    betCount: 33,
    betAmount: 6600,
    validBet: 6600,
    jc: 0,
    jp: 0,
    winAmount: 7000,
    lossAmount: -400,
    jcJpTotal: 0,
    revenueAmount: 0,
    status: 'auditing',
  },
  {
    key: '14',
    agentLevel: '1 / 6 (3)',
    agentName: 'LUCKY_CAT',
    agentDesc: '(透支-(信用/成數代理-外單位))',
    category: '體育',
    provider: 'OB',
    jpSettlement: '停用',
    method: '月結',
    date: '2025/07/31',
    betCount: 12,
    betAmount: 15000,
    validBet: 15000,
    jc: 0,
    jp: 0,
    winAmount: 10000,
    lossAmount: 5000,
    jcJpTotal: 0,
    revenueAmount: 300,
    status: 'unpaid',
  },
  {
    key: '15',
    agentLevel: '1 / 4 (8)',
    agentName: 'FMCA',
    agentDesc: '(金流/成數代理-主站)',
    category: '電子',
    provider: 'RSG',
    jpSettlement: '啟用',
    method: '週結',
    date: '2025/07/17',
    betCount: 50,
    betAmount: 5000,
    validBet: 5000,
    jc: 25,
    jp: 100,
    winAmount: 1000,
    lossAmount: 4000,
    jcJpTotal: 125,
    revenueAmount: 240,
    status: 'paid',
  },
  {
    key: '16',
    agentLevel: '1 / 7 (40)',
    agentName: 'XOUT_SUB',
    agentDesc: '(金流/成數代理-子站)',
    category: '真人',
    provider: 'SA',
    jpSettlement: '停用',
    method: '月結',
    date: '2025/07/31',
    betCount: 88,
    betAmount: 90000,
    validBet: 90000,
    jc: 0,
    jp: 0,
    winAmount: 45000,
    lossAmount: 45000,
    jcJpTotal: 0,
    revenueAmount: 2700,
    status: 'unpaid',
  },
  {
    key: '17',
    agentLevel: '1 / 2 (6)',
    agentName: 'DRAGON',
    agentDesc: '(金流/返水代理-主站)',
    category: '電子',
    provider: 'GR',
    jpSettlement: '停用',
    method: '週結',
    date: '2025/07/17',
    betCount: 10,
    betAmount: 2000,
    validBet: 2000,
    jc: 0,
    jp: 0,
    winAmount: 2000,
    lossAmount: 0,
    jcJpTotal: 0,
    revenueAmount: 0,
    status: 'paid',
  },
  {
    key: '18',
    agentLevel: '1 / 4 (12)',
    agentName: 'XFW',
    agentDesc: '(金流/成數+返水代理-外單位)',
    category: '電子',
    provider: 'BNG',
    jpSettlement: '啟用',
    method: '月結',
    date: '2025/07/31',
    betCount: 60,
    betAmount: 7500,
    validBet: 7500,
    jc: 30,
    jp: 0,
    winAmount: 5000,
    lossAmount: 2500,
    jcJpTotal: 30,
    revenueAmount: 150,
    status: 'auditing',
  },
  {
    key: '19',
    agentLevel: '1 / 5 (3)',
    agentName: 'W02_TEST',
    agentDesc: '(透支-(信用/成數代理-外單位))',
    category: '體育',
    provider: 'CMD',
    jpSettlement: '停用',
    method: '月結',
    date: '2025/07/31',
    betCount: 5,
    betAmount: 10000,
    validBet: 9800,
    jc: 0,
    jp: 0,
    winAmount: 5000,
    lossAmount: 4800,
    jcJpTotal: 0,
    revenueAmount: 288,
    status: 'unpaid',
  },
  {
    key: '20',
    agentLevel: '1 / 3 (8)',
    agentName: 'RICH_MAN',
    agentDesc: '(金流/成數代理-VIP)',
    category: '電子',
    provider: 'JILI',
    jpSettlement: '啟用',
    method: '週結',
    date: '2025/07/17',
    betCount: 400,
    betAmount: 50000,
    validBet: 50000,
    jc: 250,
    jp: 5000,
    winAmount: 30000,
    lossAmount: 20000,
    jcJpTotal: 5250,
    revenueAmount: 1200,
    status: 'unpaid',
  },
  {
    key: '21',
    agentLevel: '1 / 4 (20)',
    agentName: 'FMCA',
    agentDesc: '(金流/成數代理-主站)',
    category: '真人',
    provider: 'WM',
    jpSettlement: '停用',
    method: '週結',
    date: '2025/07/24',
    betCount: 70,
    betAmount: 35000,
    validBet: 35000,
    jc: 0,
    jp: 0,
    winAmount: 15000,
    lossAmount: 20000,
    jcJpTotal: 0,
    revenueAmount: 1200,
    status: 'unpaid',
  },
  {
    key: '22',
    agentLevel: '1 / 6 (9)',
    agentName: 'ACE_TEAM',
    agentDesc: '(金流/返水代理-測試)',
    category: '電子',
    provider: 'KA',
    jpSettlement: '停用',
    method: '月結',
    date: '2025/07/31',
    betCount: 18,
    betAmount: 1800,
    validBet: 1800,
    jc: 0,
    jp: 0,
    winAmount: 200,
    lossAmount: 1600,
    jcJpTotal: 0,
    revenueAmount: 96,
    status: 'unpaid',
  },
  {
    key: '23',
    agentLevel: '1 / 7 (55)',
    agentName: 'XOUT',
    agentDesc: '(金流/成數代理-外單位)',
    category: '電子',
    provider: 'FC',
    jpSettlement: '停用',
    method: '月結',
    date: '2025/07/31',
    betCount: 99,
    betAmount: 4500,
    validBet: 4500,
    jc: 0,
    jp: 0,
    winAmount: 4000,
    lossAmount: 500,
    jcJpTotal: 0,
    revenueAmount: 30,
    status: 'paid',
  },
  {
    key: '24',
    agentLevel: '1 / 5 (2)',
    agentName: 'W02',
    agentDesc: '(透支-(信用/成數代理-外單位))',
    category: '真人',
    provider: 'OG',
    jpSettlement: '停用',
    method: '月結',
    date: '2025/07/31',
    betCount: 3,
    betAmount: 6000,
    validBet: 6000,
    jc: 0,
    jp: 0,
    winAmount: 3000,
    lossAmount: 3000,
    jcJpTotal: 0,
    revenueAmount: 180,
    status: 'unpaid',
  },
  {
    key: '25',
    agentLevel: '1 / 4 (15)',
    agentName: 'XFW',
    agentDesc: '(金流/成數+返水代理-外單位)',
    category: '電子',
    provider: 'SP',
    jpSettlement: '啟用',
    method: '月結',
    date: '2025/07/31',
    betCount: 250,
    betAmount: 12500,
    validBet: 12500,
    jc: 60,
    jp: 200,
    winAmount: 8000,
    lossAmount: 4500,
    jcJpTotal: 260,
    revenueAmount: 270,
    status: 'unpaid',
  },
]

export const MOCK_BET_DETAILS: BetDetailType[] = [
  {
    key: 'd1',
    playerName: '馬佩琳',
    validBet: 1000,
    winAmount: 0,
    lossAmount: 1000,
  },
]

export const MOCK_JC_DETAILS: JcDetailType[] = [
  {
    key: 'j1',
    provider: 'RSG',
    validBet: 1000,
    jcRate: 0.5,
    jcAmount: 5,
  },
]

export const MOCK_REVENUE_DETAILS: RevenueDetailType[] = [
  {
    key: 'r1',
    provider: 'ATG',
    validBet: 1000,
    rate: 0.06,
    jcJp: 0,
    amount: 60,
  },
]
